#1.tau_X=0 tauY=-0.4-0.4 theta=-0.4
rm(list = ls())
library(tidyr)
library(ggplot2)
library(ggsci)
library(gridExtra)
theta_list_star=c(0.2)
tauY_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
#theta_list_star=c(-0.8,-0.6,-0.4,-0.2,-0.1,-0.05,0,0.05,0.1,0.2,0.4,0.6,0.8)
#tauY_list=c(-0.8,-0.6,-0.4,-0.2,-0.1,-0.05,0,0.05,0.1,0.2,0.4,0.6,0.8)
#theta_list=c(-0.2,-0.05,-0.1,0,0.05,0.1,0.2)
tauX_list=c(0)
#theta_list_star=c(-0.2,-0.05,-0.1,0,0.05,0.1,0.2)
M=100000

g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}

coverage_calculation<-function(true,sd,est)
{
  upper=est+1.96*sd
  lower=est-1.96*sd
  coverage=sum((upper>=true)&(lower<=true))/length(est)
  return(coverage)
}

power_calculation<-function(true,sd,est)
{
  upper=est+1.96*sd
  lower=est-1.96*sd
  power_result=c()
  for( i in (1:length(est)))
  {
    sig=0
    upper_est=upper[i]
    lower_est=lower[i]
    if(lower_est>0)
    {

      sig=1
    }
    if(upper_est<0)
    {
      sig=1
    }
    power_result=c(power_result,sig)
  }
  power=sum(power_result)/length(est)
  return(power)
}
abias<-function(theta_rerandlist,theta)
{

  return((mean(theta_rerandlist)-theta))
}


for(theta in theta_list_star)
{
  for (tauX in tauX_list)
  {
    #proposed estimator using proposed se estimator
    ## power
    theta_rerand_power=c()
    tauy_rerand_power=c()
    taux_rerand_power=c()
    tau_rerand_power=c()
    theta_rerand_se_l=c()
    tauy_rerand_se_l=c()
    tau_rerand_se_l=c()
    #bias
    tauy_rerand_abias=c()
    tau_rerand_abias=c()
    ## coverage
    theta_rerand_coverage=c()
    tauy_rerand_coverage=c()
    taux_rerand_coverage=c()
    tau_rerand_coverage=c()
    # mvmr with measurement error correction using MCSD
    ## power
    theta_mvmr_power=c()
    tauy_mvmr_power=c()
    taux_mvmr_power=c()
    tau_mvmr_power=c()
    ## coverage
    theta_mvmr_coverage=c()
    tauy_mvmr_coverage=c()
    tau_mvmr_coverage=c()
    taux_mvmr_coverage=c()
    #bias
    tauy_mvmr_abias=c()
    tau_mvmr_abias=c()
    theta_mvmr_correct_se_l=c()
    tauy_mvmr_correct_se_l=c()
    tau_mvmr_correct_se_l=c()
    # mvmr  without measurement error correction using se generated by mvmr package

    ## power
    theta_mvmr_power_ivw=c()
    tauy_mvmr_power_ivw=c()
    taux_mvmr_power_ivw=c()
    tau_mvmr_power_ivw=c()
    ## coverage
    theta_mvmr_coverage_ivw=c()
    tauy_mvmr_coverage_ivw=c()
    tau_mvmr_coverage_ivw=c()
    taux_mvmr_coverage_ivw=c()
    #bias
    tauy_mvmr_abias_ivw=c()
    tau_mvmr_abias_ivw=c()
    theta_mvmr_se_l=c()
    tauy_mvmr_se_l=c()
    tau_mvmr_se_l=c()
    # 2 step-mr

    ## power
    theta_2step_power=c()
    tauy_2step_power=c()
    taux_2step_power=c()
    tau_2step_power=c()
    ## coverage
    theta_2step_coverage=c()
    tauy_2step_coverage=c()
    tau_2step_coverage=c()
    taux_2step_coverage=c()
    #bias
    tauy_2step_abias=c()
    tau_2step_abias=c()
    theta_2step_se_l=c()
    tauy_2step_se_l=c()
    tau_2step_se_l=c()
    # difference mr

    ## power
    total_effect_power=c()
    tau_difference_power=c()
    ## coverage
    total_effect_coverage=c()
    tau_difference_coverage=c()
    #bias
    total_difference_abias=c()
    tau_difference_abias=c()
    tau_difference_se_l=c()
    for (tauy in tauY_list)
    {

      # Please change to you own laptop directory
      tau=tauX*tauy
      data_path=paste0("D:/Research/structural equation/ResultOCToriginal/simudesign2pi1=0.005pi3=0.0150.5e10-41e-4theta=",theta,"tauY=",tauy,"tauX=",tauX,"M=",M,".Rdata")
      load(data_path)
      abias<-function(theta_rerandlist,theta)
      {

        return((mean(theta_rerandlist)-theta))
      }
      tauY_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      theta_list_star=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      tauy_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      ##rerand power and coverage
      theta_power=power_calculation(theta,result$thetase,result$thetarerand)
      theta_coverage=coverage_calculation(theta,result$thetase,result$thetarerand)
      theta_rerand_power=c(theta_rerand_power,theta_power)
      theta_rerand_coverage=c(theta_rerand_coverage,theta_coverage)

      tauy_power=power_calculation(tauy,result$tauyse,result$tauyrerand)
      tauy_coverage=coverage_calculation(tauy,result$tauyse,result$tauyrerand)
      tauy_rerand_power=c(tauy_rerand_power,tauy_power)
      tauy_rerand_coverage=c(tauy_rerand_coverage,tauy_coverage)
      tauy_rerand_abias=c(tauy_rerand_abias,abias(result$tauyrerand,tauy))

      tau_power=power_calculation(tau,result$tause,result$taurerand)
      tau_coverage=coverage_calculation(tau,result$tause,result$taurerand)
      tau_rerand_power=c(tau_rerand_power,tau_power)
      tau_rerand_coverage=c(tau_rerand_coverage,tau_coverage)

      tau_rerand_abias=c(tau_rerand_abias,abias(result$taurerand,tau))

      taux_power=power_calculation(tauX,result$tauxse,result$tauxrerand)
      taux_coverage=coverage_calculation(tauX,result$tauxse,result$tauxrerand)
      taux_rerand_power=c(taux_rerand_power,taux_power)
      taux_rerand_coverage=c(taux_rerand_coverage,taux_coverage)

      theta_rerand_se_l=c( theta_rerand_se_l,sd(result$thetarerand))
      tauy_rerand_se_l=c(tauy_rerand_se_l,sd(result$tauyrerand))
      tau_rerand_se_l=c(tau_rerand_se_l,sd(result$taurerand))


      ## mvmr correction measurement error with MCSD to show power and coverage

      theta_power=power_calculation(theta,mc_sd[5],result$mvmr_theta)
      theta_coverage=coverage_calculation(theta,mc_sd[5],result$mvmr_theta)
      theta_mvmr_power=c(theta_mvmr_power,theta_power)
      theta_mvmr_coverage=c(theta_mvmr_coverage,theta_coverage)
      tauy_power=power_calculation(tauy,mc_sd[7],result$mvmr_tauY)
      tauy_coverage=coverage_calculation(tauy,mc_sd[7],result$mvmr_tauY)
      tauy_mvmr_power=c(tauy_mvmr_power,tauy_power)
      tauy_mvmr_coverage=c(tauy_mvmr_coverage,tauy_coverage)
      taux_power=power_calculation(tauX,mc_sd[6],result$mvmr_tauX)
      taux_coverage=coverage_calculation(tauX,mc_sd[6],result$mvmr_tauX)
      taux_mvmr_power=c(taux_mvmr_power,taux_power)
      taux_mvmr_coverage=c(taux_mvmr_coverage,taux_coverage)
      tau_power=power_calculation(tau,mc_sd[8],result$mvmr_tau)
      tau_coverage=coverage_calculation(tau,mc_sd[8],result$mvmr_tau)
      tau_mvmr_power=c(tau_mvmr_power,tau_power)
      tau_mvmr_coverage=c(tau_mvmr_coverage,tau_coverage)
      tauy_mvmr_abias=c(tauy_mvmr_abias,abias(result$mvmr_tauY,tauy))
      tau_mvmr_abias=c(tau_mvmr_abias,abias(result$mvmr_tau,tau))
      theta_mvmr_correct_se_l=c(theta_mvmr_correct_se_l,sd(result$mvmr_theta))
      tauy_mvmr_correct_se_l=c(tauy_mvmr_correct_se_l,sd(result$mvmr_tauY))
      tau_mvmr_correct_se_l=c(tau_mvmr_correct_se_l,sd(result$mvmr_tau))
      # mvmr  without measurement error correction using se generated by mvmr package

      ## power
      theta_power=power_calculation(theta,result$mvmrIVW_theta_se,result$mvmrIVW_theta)
      theta_coverage=coverage_calculation(theta,result$mvmrIVW_theta_se,result$mvmrIVW_theta)
      tauy_power=power_calculation(tauy,result$mvmrIVW_tauY_se,result$mvmrIVW_tauY)
      tauy_coverage=coverage_calculation(tauy,result$mvmrIVW_tauY_se,result$mvmrIVW_tauY)
      taux_power=power_calculation(tauX,result$mvmrIVW_tauX_se,result$mvmrIVW_tauX)
      taux_coverage=coverage_calculation(tauX,result$mvmrIVW_tauX_se,result$mvmrIVW_tauX)
      ##using mcsd
      tau_power=power_calculation(tau,mc_sd[12],result$mvmrIVW_tau)
      tau_coverage=coverage_calculation(tau,mc_sd[12],result$mvmrIVW_tau)

      theta_mvmr_power_ivw=c(theta_mvmr_power_ivw,theta_power)
      tauy_mvmr_power_ivw=c(tauy_mvmr_power_ivw,tauy_power)
      taux_mvmr_power_ivw=c(taux_mvmr_power_ivw,taux_power)
      tau_mvmr_power_ivw=c(tau_mvmr_power_ivw,tau_power)
      ## coverage
      theta_mvmr_coverage_ivw=c(theta_mvmr_coverage_ivw,theta_coverage)
      tauy_mvmr_coverage_ivw=c(tauy_mvmr_coverage_ivw,tauy_coverage)
      tau_mvmr_coverage_ivw=c(tau_mvmr_coverage_ivw,tau_coverage)
      taux_mvmr_coverage_ivw=c(taux_mvmr_coverage_ivw,taux_coverage)
      #bias
      tauy_mvmr_abias_ivw=c(tauy_mvmr_abias_ivw,abias(result$mvmrIVW_tauY,tauy))
      tau_mvmr_abias_ivw=c(tau_mvmr_abias_ivw,abias(result$mvmrIVW_tau,tau))
      theta_mvmr_se_l=c( theta_mvmr_se_l,sd(result$mvmrIVW_theta))
      tauy_mvmr_se_l=c(tauy_mvmr_se_l,sd(result$mvmrIVW_tauY))

      # 2 step-mr

      ## power
      tauX_power=power_calculation(tauX,result$`2step_tauX_sd`,result$`2step_tauX`)
      tauY_power=power_calculation(tauy,result$`2step_tauY_sd`,result$`2step_tauY`)
      tau_power=power_calculation(tau,result$`2step_tau_sd`,result$`2step_tau`)

      tauy_2step_power=c(tauy_2step_power,tauY_power)
      taux_2step_power=c(taux_2step_power,tauX_power)
      tau_2step_power=c(tau_2step_power,tau_power)
      ## coverage
      tauX_coverage=coverage_calculation(tauX,result$`2step_tauX_sd`,result$`2step_tauX`)
      tauY_coverage=coverage_calculation(tauy,result$`2step_tau_sd`,result$`2step_tauY`)
      tau_coverage=coverage_calculation(tau,result$`2step_tau_sd`,result$`2step_tau`)


      tauy_2step_coverage=c(tauy_2step_coverage,tauY_coverage)
      tau_2step_coverage=c(tau_2step_coverage,tau_coverage)
      taux_2step_coverage=c(taux_2step_coverage,tauX_coverage)
      tauy_2step_abias=c(tauy_2step_abias,abias(result$`2step_tauY`,tauy))
      tau_2step_abias=c(tau_2step_abias,abias(result$`2step_tau`,tau))

      tauy_2step_se_l=c(tauy_2step_se_l,sd(result$`2step_tauY`))
      tau_2step_se_l=c(tau_2step_se_l,sd(result$`2step_tau`))
      # difference mr

      ## power
      total_coverage=coverage_calculation(tau+theta,result$total_effect_sd,result$total_effect)
      tau_coverage=coverage_calculation(tau,mc_sd[17],result$difference_tau)
      total_power=power_calculation(tau+theta,result$total_effect_sd,result$total_effect)
      tau_power=power_calculation(tau,mc_sd[17],result$difference_tau)

      total_effect_power=c(total_effect_power,total_power)
      tau_difference_power=c(tau_difference_power,tau_power)
      ## coverage


      total_effect_coverage=c(total_effect_coverage,total_coverage)
      tau_difference_coverage=c(tau_difference_coverage,tau_coverage)

      total_difference_abias=c(total_difference_abias,abias(result$total_effect,tau+theta))
      tau_difference_abias=c(tau_difference_abias,abias(result$difference_tau,tau))
      tau_difference_se_l=c( tau_difference_se_l,sd(result$difference_tau))




    }
    theta_list_star=c(0.2)
    tauy_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
    #coverage_final=data.frame(cbind(theta_rerand_coverage,theta_mvmr_coverage,theta_mvmr_coverage_ivw,theta_2step_coverage,theta_list_star))
    #power_final=data.frame(cbind(theta_rerand_power,theta_mvmr_power,theta_mvmr_power_ivw,theta_2step_power,theta_list_star))
    #tauy_list=c(-0.2,-0.1,-0.05,0,0.05,0.1,0.2)
    coverage_final=data.frame(cbind(tauy_rerand_coverage,tauy_mvmr_coverage,tauy_mvmr_coverage_ivw,tauy_2step_coverage,tauy_list))
    power_final=data.frame(cbind(tauy_rerand_power,tauy_mvmr_power,tauy_mvmr_power_ivw,tauy_2step_power,tauy_list))
    colnames(power_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    colnames(coverage_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    #colnames(power_final)=c("Rerand","MVMR(No measurement error)","MVMR-IVW","theta_list_star")
    #colnames(coverage_final)=c("Rerand","MVMR(No measurement error)","MVMR-IVW","theta_list_star")

    coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -tauy_list)
    #coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -theta_list_star)
    power.plot =power_final %>% gather(key = Method, value = Power, -tauy_list)
    sd_final=data.frame(cbind(tauy_rerand_se_l,tauy_mvmr_correct_se_l,tauy_mvmr_se_l,tauy_2step_se_l,tauy_list))
    power_final=data.frame(cbind(tauy_rerand_power,tauy_mvmr_power,tauy_mvmr_power_ivw,tauy_2step_power,tauy_list))
    colnames(power_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    colnames(coverage_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    colnames(sd_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    abias_final=data.frame(cbind(tauy_rerand_abias,tauy_mvmr_abias,tauy_mvmr_abias_ivw,tauy_2step_abias,tauy_list))
    colnames(abias_final)=c("MAGIC","DMVMR","MVMR-IVW","Two-step MR","tauy_list")
    abias.plot =abias_final %>% gather(key = Method, value = Bias, -tauy_list)
    sd.plot =sd_final %>% gather(key = Method, value = MCSD, -tauy_list)
    coverage.plot[,"Method"] <- factor(   coverage.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW","Two-step MR"))
    power.plot[,"Method"] <- factor(   power.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW","Two-step MR"))
    abias.plot[,"Method"] <- factor(   abias.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW","Two-step MR"))
    sd.plot[,"Method"] <- factor(   sd.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW","Two-step MR"))

    #power.plot =power_final %>% gather(key = Method, value = Power, - theta_list_star)
    p1<-ggplot(subset(power.plot, Method != "DMVMR"), aes(x=tauy_list, y=Power, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.05) +   scale_y_continuous(breaks = c(0.05,0.25,0.5,0.75,1),labels = scales::number_format(accuracy = 0.01),limits = c(0,1))  + scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      ylim(0, 1)+
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Power",
           x = expression(paste("Causal (direct) effect size (",tau[Y],")",sep=""))) + guides(col =
                                                                                                guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p2<-ggplot(subset(coverage.plot, Method != "DMVMR"), aes(x=tauy_list, y=Coverage, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.95) +   scale_y_continuous(breaks = c(0,0.25,0.5,0.75, 0.95),labels = scales::number_format(accuracy = 0.01),limits = c(0,1))+scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Coverage",
           x = expression(paste("Causal (direct) effect size (",tau[Y],")",sep=""))) + guides(col =guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p3<-ggplot(abias.plot, aes(x=tauy_list, y=Bias, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) + geom_point(aes(shape =Method), size = 2)+   scale_y_continuous(breaks = c(-0.04,-0.020,0,0.02,0.040,0.06,0.08,0.1,0.12),labels = scales::number_format(accuracy = 0.001),limits = c(-0.04,0.12))  + scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="")) ,
           y = "Bias",
           x = expression(paste("Causal (direct) effect size (",tau[Y],")",sep=""))) + guides(col =
                                                                                                guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p4<-ggplot(sd.plot, aes(x=tauy_list, y=MCSD, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2) +   scale_y_continuous(breaks = c(0,0.01,0.02,0.03,0.04,0.05),labels = scales::number_format(accuracy = 0.001),limits=c(0,0.05))+ scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ) ,
           y = "MCSD",
           x = expression(paste("Causal (direct) effect size (",tau[Y],")",sep=""))) + guides(col = guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    # Manually specify legend colors and labels
    p1 <- p1 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p2 <- p2 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p3 <- p3 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p4 <- p4 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))

    tau_list_star=tauy_list*tauX
    #coverage_final=data.frame(cbind(theta_rerand_coverage,theta_mvmr_coverage,theta_mvmr_coverage_ivw,theta_2step_coverage,theta_list_star))
    #power_final=data.frame(cbind(theta_rerand_power,theta_mvmr_power,theta_mvmr_power_ivw,theta_2step_power,theta_list_star))
    #tauy_list=c(-0.2,-0.1,-0.05,0,0.05,0.1,0.2)
    coverage_final=data.frame(cbind(tau_rerand_coverage,tau_difference_coverage,tau_2step_coverage,tau_list_star))
    power_final=data.frame(cbind(tau_rerand_power,tau_difference_power,tau_2step_power,tau_list_star))
    colnames(power_final)=c("MAGIC","MVMR-IVW","Two-step MR","tau_list")
    colnames(coverage_final)=c("MAGIC","MVMR-IVW","Two-step MR","tau_list")
    #colnames(power_final)=c("Rerand","MVMR(No measurement error)","MVMR-IVW","theta_list_star")
    #colnames(coverage_final)=c("Rerand","MVMR(No measurement error)","MVMR-IVW","theta_list_star")

    coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -tau_list)
    #coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -theta_list_star)
    power.plot =power_final %>% gather(key = Method, value = Power, -tau_list)
    abias_final=data.frame(cbind(tau_rerand_abias,tau_difference_abias,tau_2step_abias,tau_list_star))
    colnames(abias_final)=c("MAGIC","MVMR-IVW","Two-step MR","tau_list")
    abias.plot =abias_final %>% gather(key = Method, value = Bias, -tau_list)
    coverage.plot[,"Method"] <- factor(   coverage.plot[,"Method"] ,levels = c("MAGIC","MVMR-IVW","Two-step MR"))
    power.plot[,"Method"] <- factor(   power.plot[,"Method"] ,levels = c("MAGIC","MVMR-IVW","Two-step MR"))
    abias.plot[,"Method"] <- factor(   abias.plot[,"Method"] ,levels = c("MAGIC","MVMR-IVW","Two-step MR"))
    sd_final=data.frame(cbind(tau_rerand_se_l,tau_difference_se_l,tau_2step_se_l,tau_list_star))
    colnames(sd_final)=c("MAGIC","MVMR-IVW","Two-step MR","tau_list")
    sd.plot =sd_final %>% gather(key = Method, value = MCSD, -tau_list)
    sd.plot[,"Method"] <- factor(   sd.plot[,"Method"] ,levels = c("MAGIC","MVMR-IVW","Two-step MR"))

    p5<-ggplot(subset(power.plot, Method != "MVMR-IVW"), aes(x=tau_list, y=Power, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.05) +   scale_y_continuous(breaks = c(0.05,0.25,0.5,0.75,1),labels = scales::number_format(accuracy = 0.01),limits = c(0,1)) + scale_shape_manual(values =c(1,2,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  "dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Power",
           x = expression(paste("Mediation effect size (",tau,")",sep=""))) + guides(col =
                                                                                       guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p6<-ggplot(subset(coverage.plot, Method != "MVMR-IVW"), aes(x=tau_list, y=Coverage, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.95) +   scale_y_continuous(breaks = c(0,0.25,0.5,0.75, 0.95),labels = scales::number_format(accuracy = 0.01),limits = c(0,1))+ scale_shape_manual(values =c(1,2,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ) ,
           y = "Coverage",
           x = expression(paste("Mediation effect size (",tau,")",sep=""))) + guides(col =
                                                                                       guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p7<-ggplot(abias.plot, aes(x=tau_list, y=Bias, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2) +   scale_y_continuous(breaks = c(-0.04,-0.020,0,0.02,0.040,0.06,0.08,0.1,0.12),labels = scales::number_format(accuracy = 0.001),limits=c(-0.04,0.12)) + scale_shape_manual(values =c(1,2,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Bias",
           x = expression(paste("Mediation effect size (",tau,")",sep=""))) + guides(col =
                                                                                       guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p8<-ggplot(sd.plot, aes(x=tau_list, y=MCSD, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2) + scale_y_continuous(breaks = c(0,0.01,0.02,0.03,0.04,0.05),labels = scales::number_format(accuracy = 0.001),limits = c(0, 0.05)) + scale_shape_manual(values =c(1,2,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(theta,"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "MCSD",
           x = expression(paste("Mediation effect size (",tau,")",sep=""))) + guides(col =
                                                                                       guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()


    p5 <- p5 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p6<- p6 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p7 <- p7 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))

    p8 <- p8 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1,  "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid","MVMR-IVW" = 'dotted',  "Two-step MR" = "dotdash"))



    #ggplot(coverage.plot, aes(x=theta_list_star, y=Coverage, color=Method,group = Method)) + geom_line(aes(linetype = Method)) +
    # geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = c(0.95)) +   scale_y_continuous(breaks = sort(c(seq(0,1, length.out=5),0.95))) + scale_shape_manual(values =c(2,3,4,5,6,7)) +  scale_linetype_manual(values = c('dashed',  'dotted','solid')) + theme_bw() +
    #  theme(axis.title = element_text(face="bold", size = rel(1.2)),
    #       axis.text = element_text( size = rel(1.2)),
    #      axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
    #     legend.position = "bottom",
    #    legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
    #    legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
    #labs(title=paste("tau_Y=",tauy,",tau_X=",tauX,sep=""),
    #    y = "Coverage",
    #   x = expression(paste("Causal effect size (",theta ,")",sep=""))) + guides(col =
    #                                                                           guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()


    #ggsave (paste0("D:/Research/structural equation/resultpower_tauYSep/pi1=pi3=0.01theta=",theta,"tauY=",tauy,"tauX=",tauX,"M=",M,"Power.png"), p1,width = 11,             # ???
    #       height = 11)
    #ggsave (paste0("D:/Research/structural equation/resultpower_tauYSep/pi1=pi3=0.01theta=",theta,"tauY=",tauy,"tauX=",tauX,"M=",M,"Coverage.png"), p1,width = 11,             # ???
    #      height = 11)
  }
}




theta_list_star=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
tauY_list=c(0.2)
#theta_list_star=c(-0.8,-0.6,-0.4,-0.2,-0.1,-0.05,0,0.05,0.1,0.2,0.4,0.6,0.8)
#tauY_list=c(-0.8,-0.6,-0.4,-0.2,-0.1,-0.05,0,0.05,0.1,0.2,0.4,0.6,0.8)
#theta_list=c(-0.2,-0.05,-0.1,0,0.05,0.1,0.2)
tauX_list=c(0)
#theta_list_star=c(-0.2,-0.05,-0.1,0,0.05,0.1,0.2)
M=100000
for (tauy in tauY_list)
{
  for (tauX in tauX_list)
  {
    #proposed estimator using proposed se estimator
    ## power
    theta_rerand_power=c()
    tauy_rerand_power=c()
    taux_rerand_power=c()
    tau_rerand_power=c()
    #bias
    theta_rerand_abias=c()
    tau_rerand_abias=c()
    ## coverage
    theta_rerand_coverage=c()
    tauy_rerand_coverage=c()
    taux_rerand_coverage=c()
    tau_rerand_coverage=c()
    theta_rerand_se_l=c()
    tauy_rerand_se_l=c()
    tau_rerand_se_l=c()
    # mvmr with measurement error correction using MCSD
    ## power
    theta_mvmr_power=c()
    tauy_mvmr_power=c()
    taux_mvmr_power=c()
    tau_mvmr_power=c()
    ## coverage
    theta_mvmr_coverage=c()
    tauy_mvmr_coverage=c()
    tau_mvmr_coverage=c()
    taux_mvmr_coverage=c()
    #bias
    theta_mvmr_abias=c()
    tau_mvmr_abias=c()
    tauy_mvmr_abias=c()

    theta_mvmr_correct_se_l=c()
    tauy_mvmr_correct_se_l=c()

    # mvmr  without measurement error correction using se generated by mvmr package

    ## power
    theta_mvmr_power_ivw=c()
    tauy_mvmr_power_ivw=c()
    taux_mvmr_power_ivw=c()
    tau_mvmr_power_ivw=c()
    ## coverage
    theta_mvmr_coverage_ivw=c()
    tauy_mvmr_coverage_ivw=c()
    tau_mvmr_coverage_ivw=c()
    taux_mvmr_coverage_ivw=c()
    #bias
    theta_mvmr_abias_ivw=c()
    tau_mvmr_abias_ivw=c()
    theta_mvmr_se_l=c()
    tauy_mvmr_se_l=c()
    tau_mvmr_se_l=c()
    # 2 step-mr

    ## power
    theta_2step_power=c()
    tauy_2step_power=c()
    taux_2step_power=c()
    tau_2step_power=c()
    ## coverage
    theta_2step_coverage=c()
    tauy_2step_coverage=c()
    tau_2step_coverage=c()
    taux_2step_coverage=c()
    #bias
    theta_2step_abias=c()
    tauy_2step_abias=c()
    tau_2step_abias=c()
    tauy_2step_se_l=c()
    tau_2step_se_l=c()
    # difference mr

    ## power
    total_effect_power=c()
    tau_difference_power=c()
    ## coverage
    total_effect_coverage=c()
    tau_difference_coverage=c()
    #bias
    total_difference_abias=c()
    tau_difference_abias=c()
    tau_difference_se_l=c()
    for (theta in theta_list_star)
    {


      tau=tauX*tauy
      data_path=paste0("D:/Research/structural equation/ResultOCToriginal/simudesign2pi1=0.005pi3=0.0150.5e10-41e-4theta=",theta,"tauY=",tauy,"tauX=",tauX,"M=",M,".Rdata")
      load(data_path)
      abias<-function(theta_rerandlist,theta)
      {

        return((mean(theta_rerandlist)-theta))
      }
      tauY_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      theta_list_star=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      tauy_list=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
      ##rerand power and coverage
      theta_power=power_calculation(theta,result$thetase,result$thetarerand)
      theta_coverage=coverage_calculation(theta,result$thetase,result$thetarerand)
      theta_rerand_power=c(theta_rerand_power,theta_power)
      theta_rerand_coverage=c(theta_rerand_coverage,theta_coverage)

      tauy_power=power_calculation(tauy,result$tauyse,result$tauyrerand)
      tauy_coverage=coverage_calculation(tauy,result$tauyse,result$tauyrerand)
      tauy_rerand_power=c(tauy_rerand_power,tauy_power)
      tauy_rerand_coverage=c(tauy_rerand_coverage,tauy_coverage)
      theta_rerand_abias=c(theta_rerand_abias,abias(result$thetarerand,theta))

      tau_power=power_calculation(tau,result$tause,result$taurerand)
      tau_coverage=coverage_calculation(tau,result$tause,result$taurerand)
      tau_rerand_power=c(tau_rerand_power,tau_power)
      tau_rerand_coverage=c(tau_rerand_coverage,tau_coverage)

      tau_rerand_abias=c(tau_rerand_abias,abias(result$taurerand,tau))

      taux_power=power_calculation(tauX,result$tauxse,result$tauxrerand)
      taux_coverage=coverage_calculation(tauX,result$tauxse,result$tauxrerand)
      taux_rerand_power=c(taux_rerand_power,taux_power)
      taux_rerand_coverage=c(taux_rerand_coverage,taux_coverage)
      theta_rerand_se_l=c( theta_rerand_se_l,sd(result$thetarerand))
      tauy_rerand_se_l=c(tauy_rerand_se_l,sd(result$tauyrerand))
      tau_rerand_se_l=c(tau_rerand_se_l,sd(result$taurerand))


      ## mvmr correction measurement error with MCSD to show power and coverage

      theta_power=power_calculation(theta,mc_sd[5],result$mvmr_theta)
      theta_coverage=coverage_calculation(theta,mc_sd[5],result$mvmr_theta)
      theta_mvmr_power=c(theta_mvmr_power,theta_power)
      theta_mvmr_coverage=c(theta_mvmr_coverage,theta_coverage)
      tauy_power=power_calculation(tauy,mc_sd[7],result$mvmr_tauY)
      tauy_coverage=coverage_calculation(tauy,mc_sd[7],result$mvmr_tauY)
      tauy_mvmr_power=c(tauy_mvmr_power,tauy_power)
      tauy_mvmr_coverage=c(tauy_mvmr_coverage,tauy_coverage)
      taux_power=power_calculation(tauX,mc_sd[6],result$mvmr_tauX)
      taux_coverage=coverage_calculation(tauX,mc_sd[6],result$mvmr_tauX)
      taux_mvmr_power=c(taux_mvmr_power,taux_power)
      taux_mvmr_coverage=c(taux_mvmr_coverage,taux_coverage)
      tau_power=power_calculation(tau,mc_sd[8],result$mvmr_tau)
      tau_coverage=coverage_calculation(tau,mc_sd[8],result$mvmr_tau)
      tau_mvmr_power=c(tau_mvmr_power,tau_power)
      tau_mvmr_coverage=c(tau_mvmr_coverage,tau_coverage)
      theta_mvmr_abias=c(theta_mvmr_abias,abias(result$mvmr_theta,theta))
      tau_mvmr_abias=c(tau_mvmr_abias,abias(result$mvmr_tau,tau))
      theta_mvmr_correct_se_l=c(theta_mvmr_correct_se_l,sd(result$mvmr_theta))
      tauy_mvmr_correct_se_l=c( tauy_mvmr_correct_se_l,sd(result$mvmr_tauY))
      # mvmr  without measurement error correction using se generated by mvmr package

      ## power
      theta_power=power_calculation(theta,result$mvmrIVW_theta_se,result$mvmrIVW_theta)
      theta_coverage=coverage_calculation(theta,result$mvmrIVW_theta_se,result$mvmrIVW_theta)
      tauy_power=power_calculation(tauy,result$mvmrIVW_tauY_se,result$mvmrIVW_tauY)
      tauy_coverage=coverage_calculation(tauy,result$mvmrIVW_tauY_se,result$mvmrIVW_tauY)
      taux_power=power_calculation(tauX,result$mvmrIVW_tauX_se,result$mvmrIVW_tauX)
      taux_coverage=coverage_calculation(tauX,result$mvmrIVW_tauX_se,result$mvmrIVW_tauX)
      ##using mcsd
      tau_power=power_calculation(tau,mc_sd[12],result$mvmrIVW_tau)
      tau_coverage=coverage_calculation(tau,mc_sd[12],result$mvmrIVW_tau)

      theta_mvmr_power_ivw=c(theta_mvmr_power_ivw,theta_power)
      tauy_mvmr_power_ivw=c(tauy_mvmr_power_ivw,tauy_power)
      taux_mvmr_power_ivw=c(taux_mvmr_power_ivw,taux_power)
      tau_mvmr_power_ivw=c(tau_mvmr_power_ivw,tau_power)
      ## coverage
      theta_mvmr_coverage_ivw=c(theta_mvmr_coverage_ivw,theta_coverage)
      tauy_mvmr_coverage_ivw=c(tauy_mvmr_coverage_ivw,tauy_coverage)
      tau_mvmr_coverage_ivw=c(tau_mvmr_coverage_ivw,tau_coverage)
      taux_mvmr_coverage_ivw=c(taux_mvmr_coverage_ivw,taux_coverage)
      #bias
      theta_mvmr_abias_ivw=c(theta_mvmr_abias_ivw,abias(result$mvmrIVW_theta,theta))
      tau_mvmr_abias_ivw=c(tau_mvmr_abias_ivw,abias(result$mvmrIVW_tau,tau))

      theta_mvmr_se_l=c( theta_mvmr_se_l,sd(result$mvmrIVW_theta))
      tauy_mvmr_se_l=c(tauy_mvmr_se_l,sd(result$mvmrIVW_tauY))

      # 2 step-mr

      ## power
      tauX_power=power_calculation(tauX,result$`2step_tauX_sd`,result$`2step_tauX`)
      tauY_power=power_calculation(tauy,result$`2step_tauY_sd`,result$`2step_tauY`)
      tau_power=power_calculation(tau,result$`2step_tau_sd`,result$`2step_tau`)

      tauy_2step_power=c(tauy_2step_power,tauY_power)
      taux_2step_power=c(taux_2step_power,tauX_power)
      tau_2step_power=c(tau_2step_power,tau_power)
      ## coverage
      tauX_coverage=coverage_calculation(tauX,result$`2step_tauX_sd`,result$`2step_tauX`)
      tauY_coverage=coverage_calculation(tauy,result$`2step_tau_sd`,result$`2step_tauY`)
      tau_coverage=coverage_calculation(tau,result$`2step_tau_sd`,result$`2step_tau`)


      tauy_2step_coverage=c(tauy_2step_coverage,tauY_coverage)
      tau_2step_coverage=c(tau_2step_coverage,tau_coverage)
      taux_2step_coverage=c(taux_2step_coverage,tauX_coverage)
      tauy_2step_abias=c(tauy_2step_abias,abias(result$`2step_tauY`,tauy))
      tau_2step_abias=c(tau_2step_abias,abias(result$`2step_tau`,tau))

      tauy_2step_se_l=c(tauy_2step_se_l,sd(result$`2step_tau`))
      tau_2step_se_l=c(tau_2step_se_l,sd(result$`2step_tau`))
      # difference mr

      ## power
      total_coverage=coverage_calculation(tau+theta,result$total_effect_sd,result$total_effect)
      tau_coverage=coverage_calculation(tau,mc_sd[17],result$difference_tau)
      total_power=power_calculation(tau+theta,result$total_effect_sd,result$total_effect)
      tau_power=power_calculation(tau,mc_sd[17],result$difference_tau)

      total_effect_power=c(total_effect_power,total_power)
      tau_difference_power=c(tau_difference_power,tau_power)
      ## coverage


      total_effect_coverage=c(total_effect_coverage,total_coverage)
      tau_difference_coverage=c(tau_difference_coverage,tau_coverage)

      total_difference_abias=c(total_difference_abias,abias(result$total_effect,tau+theta))
      tau_difference_abias=c(tau_difference_abias,abias(result$difference_tau,tau))
      tau_difference_se_l=c(tau_difference_se_l,sd(result$difference_tau))



    }

    theta_list_star=c(-0.2,-0.15,-0.1,-0.05,0,0.05,0.1,0.15,0.2)
    tauy_list=c(0.2)
    coverage_final=data.frame(cbind(theta_rerand_coverage,theta_mvmr_coverage,theta_mvmr_coverage_ivw,theta_list_star))
    power_final=data.frame(cbind(theta_rerand_power,theta_mvmr_power,theta_mvmr_power_ivw,theta_list_star))
    #tauy_list=c(-0.2,-0.1,-0.05,0,0.05,0.1,0.2)
    #coverage_final=data.frame(cbind(tauy_rerand_coverage,tauy_mvmr_coverage,tauy_mvmr_coverage_ivw,tauy_2step_coverage,tauy_list))
    #power_final=data.frame(cbind(tauy_rerand_power,tauy_mvmr_power,tauy_mvmr_power_ivw,tauy_2step_power,tauy_list))
    #colnames(power_final)=c("Proposed","MVMR(No measurement error)","MVMR-IVW","Two-step MR","tauy_list")
    #colnames(coverage_final)=c("Proposed","MVMR(No measurement error)","MVMR-IVW","Two-step MR","tauy_list")
    colnames(power_final)=c("MAGIC","DMVMR","MVMR-IVW","theta_list_star")
    colnames(coverage_final)=c("MAGIC","DMVMR","MVMR-IVW","theta_list_star")

    #coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -tauy_list)
    coverage.plot =coverage_final %>% gather(key = Method, value = Coverage, -theta_list_star)
    #power.plot =power_final %>% gather(key = Method, value = Power, -tauy_list)
    abias_final=data.frame(cbind(theta_rerand_abias,theta_mvmr_abias,theta_mvmr_abias_ivw,theta_list_star))
    colnames(abias_final)=c("MAGIC","DMVMR","MVMR-IVW","theta_list_star")
    abias.plot =abias_final %>% gather(key = Method, value = Bias, -theta_list_star)

    power.plot =power_final %>% gather(key = Method, value = Power, - theta_list_star)
    coverage.plot[,"Method"] <- factor(   coverage.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW"))
    power.plot[,"Method"] <- factor(   power.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW"))
    abias.plot[,"Method"] <- factor(   abias.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW"))
    sd_final=data.frame(cbind(theta_rerand_se_l,theta_mvmr_correct_se_l,theta_mvmr_se_l,theta_list_star))
    colnames(sd_final)=c("MAGIC","DMVMR","MVMR-IVW","theta_list_star")
    sd.plot =sd_final %>% gather(key = Method, value = MCSD, -theta_list_star)
    sd.plot[,"Method"] <- factor(   sd.plot[,"Method"] ,levels = c("MAGIC","DMVMR","MVMR-IVW"))

    p9<-ggplot(subset(power.plot, Method != "DMVMR"), aes(x=theta_list_star, y=Power, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.05) +   scale_y_continuous(breaks = c(0.05,0.25,0.5,0.75,1),labels = scales::number_format(accuracy = 0.01),limits = c(0, 1)) + scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(tau[Y],"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Power",
           x = expression(paste("Causal (direct) effect size (",theta,")",sep=""))) + guides(col =
                                                                                               guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p10<-ggplot(subset(coverage.plot, Method != "DMVMR"), aes(x=theta_list_star, y=Coverage, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2)+geom_hline(yintercept = 0.95) +   scale_y_continuous(breaks = c(0,0.25,0.5,0.75, 0.95),labels = scales::number_format(accuracy = 0.01),limits = c(0, 1)) + scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(tau[Y],"=0.2,"," ", tau[X],"=0.6",sep="") ),
           y = "Coverage",
           x = expression(paste("Causal (direct) effect size (",theta,")",sep=""))) + guides(col =
                                                                                               guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p11<-ggplot(abias.plot, aes(x=theta_list_star, y=Bias, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2) +   scale_y_continuous(breaks = c(-0.04,-0.020,0,0.02,0.040,0.06,0.08,0.1,0.12),labels = scales::number_format(accuracy = 0.001),limits = c(-0.04,0.12)) + scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(tau[Y],"=0.2,"," ", tau[X],"=0.6",sep="") ) ,
           y = "Bias",
           x = expression(paste("Causal (direct) effect size (",theta,")",sep=""))) + guides(col =
                                                                                               guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()

    p12<-ggplot(sd.plot, aes(x=theta_list_star, y=MCSD, color=Method,group = Method)) + geom_line(aes(linetype = Method),linewidth=1.2) +
      geom_point(aes(shape =Method), size = 2) +   scale_y_continuous(breaks = c(0,0.01,0.02,0.03,0.04,0.05),labels = scales::number_format(accuracy = 0.001),limits = c(0, 0.05))+ scale_shape_manual(values =c(1,2,3,4,5,6,7)) +  scale_linetype_manual(values = c("solid",'dashed',  'dotted',"dashed")) + theme_bw() +
      theme(axis.title = element_text(face="bold", size = rel(1.2)),
            axis.text = element_text( size = rel(1.2)),
            axis.title.y = element_text(margin = margin(t = 0, r = 10, b = 0, l = 0, unit='pt')),
            legend.position = "bottom",
            legend.title = element_text(face = "bold", margin = margin(r = 10, unit = 'pt'), size = rel(1.2)),
            legend.text = element_text(margin = margin(r = 10, unit = 'pt'), size = rel(1.2) ) )  +
      labs(title=expression(paste(tau[Y],"=0.2,"," ", tau[X],"=0.6",sep="") ) ,
           y = "MCSD",
           x = expression(paste("Causal (direct) effect size (",theta,")",sep=""))) + guides(col =
                                                                                               guide_legend(nrow = 1),shape =guide_legend(nrow = 1) )  + scale_color_npg() + scale_fill_npg()


    p9 <- p9 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p10 <- p10 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p11 <- p11 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF", "MVMR-IVW" = "#1E90FF", "Two-step MR" = "#FFBE7A")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2, "MVMR-IVW" = 3, "Two-step MR" = 4))+  scale_linetype_manual(values = c("MAGIC" = "solid", "DMVMR" = 'dashed', "MVMR-IVW" = 'dotted', "Two-step MR" = "dotdash"))
    p12 <- p12 +
      scale_color_manual(values = c("MAGIC" = "#624c7c", "DMVMR" = "#98F5FF",  "MVMR-IVW" = "#1E90FF")) +scale_shape_manual(values =c("MAGIC" = 1, "DMVMR" = 2,  "MVMR-IVW" = 3))+  scale_linetype_manual(values = c("MAGIC" = "solid",   "DMVMR" = 'dashed',"MVMR-IVW" = 'dotted'))
  }
}
# Please change to you own laptop directory
jpeg(paste0("D:\\Research\\structural equation\\Summary_Plot\\tauX=0_pi1=0.005_pi3=0.015simu2",".jpeg"),  units="in", width=12.5, height=8, res=300)
mylegend<-g_legend(p3)
grid.arrange(arrangeGrob(p1 + theme(legend.position="none"),
                         p5 + theme(legend.position="none"),
                         p9 + theme(legend.position="none"),
                        # p4 + theme(legend.position="none"),
                         nrow=1),  arrangeGrob(p2 + theme(legend.position="none"),
                                               p6 + theme(legend.position="none"),
                                               p10+ theme(legend.position="none"),
                                              # p8+ theme(legend.position="none"),
                                               nrow=1), arrangeGrob(p3 + theme(legend.position="none"),
                                                                    p7 + theme(legend.position="none"),
                                                                    p11 + theme(legend.position="none"),
                                                                   # p12 + theme(legend.position="none"),
                                                                    nrow=1),  arrangeGrob(p4 + theme(legend.position="none"),
                                                                                          p8 + theme(legend.position="none"),
                                                                                          p12 + theme(legend.position="none"),nrow=1), mylegend, nrow=5,heights=c(10,10,10,10,1.5))

dev.off()
